Blog/BlogVarellaMotos/Models/BlogPostViewModel.cs
using BlogVarellaMotos.DAL;
using BlogVarellaMotos.Framework;
using System;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Web;
using System.Web.Mvc;

namespace BlogVarellaMotos.Models
{
    public class BlogPostViewModel
    {
        [Key]
        public int Id { get;  set; }
        
        private string title;

        [Required]
        [MaxLength(150)]
        [Display(Name = "Título")]
        public string Title
        {
            get
            {
                return this.title;
            }
            set
            {
                this.title = value;
                this.SlugTitle = Util.GenerateSlug(this.title);
            }

        }
        [Required]
        [MaxLength(100)]
        [Display(Name = "Subtítulo")]
        public string SubTitle { get; set; }

        public readonly string NomeAutor;

        [Required]
        [AllowHtml]
        [Display(Name="Texto")]
        public string Body { get; set; }

        public readonly DateTime DateCreated;

         [Display(Name = "Descrição SEO")]
         [MaxLength(400)]
        public string MetaDescription { get; set; }

         private string imagePath;

         [MaxLength(255)]
         [DataType(DataType.ImageUrl)]
         public string ImagePath { get; set; }

         //[MaxLength(255)]
         //[DataType(DataType.ImageUrl)]
         //public string ImagePath
         //{
         //    get
         //    {
         //        return string.Format("/Jonathan{0}", imagePath);
         //    }
         //    set
         //    {
         //        imagePath = value;
         //    }
         //}

        [NotMapped]
        [DataType(DataType.Upload)]
        public HttpPostedFileBase UploadImage { get; set; }
        
        [MaxLength(150)]
        public string SlugTitle { get; private set; }

        public readonly DateTime? DateModified;


        [MaxLength(50)]
        public readonly string ModifiedById;

      
        public BlogPostViewModel()
        {
          
        }
        public BlogPostViewModel(BlogPost blogPost)
        {
            this.Id = blogPost.Id;
            this.ImagePath = blogPost.ImagePath;
            this.MetaDescription = blogPost.MetaDescription;
            this.SubTitle = blogPost.SubTitle;
            this.Title = blogPost.Title;
            this.SlugTitle = blogPost.SlugTitle;
            this.NomeAutor = string.IsNullOrEmpty(blogPost.AspNetUsers.Name) ? blogPost.AspNetUsers.UserName : blogPost.AspNetUsers.Name;
            this.Body = blogPost.Body;
            this.DateCreated = blogPost.DateCreated;
            this.DateModified = blogPost.DateModified;
            this.ModifiedById = blogPost.ModifiedById;           
        }
                
       

    }
}

Blog/BlogVarellaMotos/Controllers/AdminController.cs
using BlogVarellaMotos.DAL;
using BlogVarellaMotos.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Microsoft.AspNet.Identity;
using PagedList;
using BlogVarellaMotos.Framework;
using System.IO;

namespace BlogVarellaMotos.Controllers
{
    [Authorize]
    public class AdminController : Controller
    {
        
        public int _take = 15;

        public ActionResult Index()
        {
            return View();
        }

        public ActionResult BlogPosts(int? pagina)
        {
            BlogVarellaMotosEntities context = new BlogVarellaMotosEntities();
            List<BlogPostViewModel> blogPosts = new List<BlogPostViewModel>();
            int paginaTamanho = 15;
            int paginaNumero = (pagina ?? 1);

            foreach (var item in context.BlogPost.OrderByDescending(x => x.Id).ToList())
            {
                BlogPostViewModel blogPost = new BlogPostViewModel(item);
                blogPosts.Add(blogPost);
            }
            // context.BlogPost.OrderBy(x => x.DateCreated).Skip(page * _take).Take(_take).ToList()
            return PartialView(blogPosts.ToPagedList(paginaNumero, paginaTamanho));
        }

        public ActionResult CreateBlogPost()
        {
            return View();
        }


        [HttpPost]
        public ActionResult CreateBlogPost(BlogPostViewModel model)
        {
            string userId = string.Empty;
            string nomeUser = string.Empty;

            if (!ModelState.IsValid)
                return View(model);

            try
            {
                using (BlogVarellaMotosEntities context = new BlogVarellaMotosEntities())
                {
                    //verifica se já existe algum artigo com esse titulo e só prossegue caso não exista
                    if(context.BlogPost.Any(x => x.Title.ToUpper().Equals(model.Title.ToUpper())))
                    {
                        ModelState.AddModelError("Title", "Já existe um artigo com esse título cadastrado.");
                        return View(model);
                    }
                    model.ImagePath = UploadImage(model.UploadImage);
                    userId = User.Identity.GetUserId();
                    var user = context.AspNetUsers.Find(userId);
                    nomeUser = string.IsNullOrEmpty(user.Name) ? user.UserName : user.Name;
                    BlogPost blogPost = new BlogPost();
                    blogPost.Create(model, user.Id);
                    context.BlogPost.Add(blogPost);
                    context.SaveChanges();                    
                };
                return RedirectToAction("Index");

            }
            catch (Exception ex)
            {
                DeleteUploadImage(model.ImagePath);
                return View();
            }
        }


        public ActionResult EditBlogPost(int id = 0)
        {
            if (id == 0)
                return RedirectToAction("Index");
            try
            {
                BlogPostViewModel blogPostViewModel = GetBlogPostViewModel(id);
                if (blogPostViewModel != null)
                {
                    return View(blogPostViewModel);
                }
            }
            catch (Exception ex)
            {
                RedirectToAction("Index");
            }
            return RedirectToAction("Index");
        }

        [HttpPost]
        public ActionResult EditBlogPost(BlogPostViewModel model)
        {
            string userId = string.Empty;
            string nomeUser = string.Empty;

            if (!ModelState.IsValid)
                return View(model);

            try
            {
                using (BlogVarellaMotosEntities context = new BlogVarellaMotosEntities())
                {
                    bool deleteOldImage = false;
                    string oldImageName = "";
                    

                    
                    //localiza o artigo om o id informado
                    BlogPost blogPost = context.BlogPost.Find(model.Id);

                    if (blogPost != null)
                    {
                        // se o cliente mudou o titulo, valida se novo titulo não existe
                        if (blogPost.Title != model.Title && context.BlogPost.Any(x => x.Title.ToUpper().Equals(model.Title.ToUpper())))
                        {
                            ModelState.AddModelError("Title", "Já existe um artigo com esse título cadastrado.");
                            return View(model);
                        }

                        if (model.UploadImage != null)
                        {
                            model.ImagePath = UploadImage(model.UploadImage);
                            deleteOldImage = true;
                            oldImageName = blogPost.ImagePath;
                        }
                        userId = User.Identity.GetUserId();
                        var user = context.AspNetUsers.Find(userId);
                        nomeUser = string.IsNullOrEmpty(user.Name) ? user.UserName : user.Name;
                        blogPost.Update(model, user.Id);
                        context.SaveChanges();

                        if (deleteOldImage)
                            DeleteUploadImage(oldImageName);
                    }




                };

                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                return RedirectToAction("Index");
            }
        }

        public ActionResult ConfirmDeleteBlogPost(int id = 0)
        {
            if (id == 0)
                return RedirectToAction("Index");

            try
            {
                BlogPostViewModel blogPost = GetBlogPostViewModel(id);
                return View(blogPost);
            }
            catch (Exception ex)
            {
                return RedirectToAction("Index");
            }
        }

       
        public ActionResult DeleteBlogPost(int id = 0)
        {
            if (id == 0)
                return RedirectToAction("Index");

            try
            {
                using (BlogVarellaMotosEntities context = new BlogVarellaMotosEntities())
                {
                    BlogPost blogPost = context.BlogPost.Find(id);
                    if (blogPost != null)
                    {
                        string oldImageName = blogPost.ImagePath;
                        context.BlogPost.Remove(blogPost);
                        context.SaveChanges();

                        DeleteUploadImage(oldImageName);
                    }
                };
                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                return View();
            }
        }

        private string UploadImage(HttpPostedFileBase image)
        {
            string relativePath = "";
            string imageName = "default.jpg";
            string imagesDir = "/imagens/Upload/";
            if (image != null && image.IsImage())
            {
                imageName = string.Format("{0}{1}", Guid.NewGuid(), Path.GetExtension(image.FileName));
                string imagePath = Path.Combine(HttpContext.Server.MapPath("~/" + imagesDir), imageName);
                image.SaveAs(imagePath);
                relativePath = imagesDir + imageName;
            }
            else
            {
                relativePath = imagesDir+imageName;
            }
            return relativePath ;
        }

        private void DeleteUploadImage(string relativePath)
        {
            if(string.IsNullOrEmpty(relativePath))
                return;
            string fullPath = Path.Combine(HttpContext.Server.MapPath("~/"), relativePath);
            if (System.IO.File.Exists(fullPath))
            {
                System.IO.File.Delete(fullPath);
            }
        }

        private BlogPostViewModel GetBlogPostViewModel(int id)
        {
            using (BlogVarellaMotosEntities context = new BlogVarellaMotosEntities())
            {
                BlogPost blogPost = context.BlogPost.Find(id);
                return new BlogPostViewModel(blogPost);
            };
        }

    }
}

Blog/BlogVarellaMotos/Controllers/BlogController.cs
using BlogVarellaMotos.DAL;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using PagedList;
using BlogVarellaMotos.Models;

namespace BlogVarellaMotos.Controllers
{
    public class BlogController : Controller
    {
        public static List<BlogPost> BlogPosts;
                
        // GET: BlogPost
        public ActionResult Index(int? pagina)
        {

            BlogVarellaMotosEntities context = new BlogVarellaMotosEntities();
            
            List<BlogPostViewModel> blogPosts = new List<BlogPostViewModel>();

                
            int paginaTamanho = 15;
            int paginaNumero = (pagina ?? 1);

            foreach (var item in context.BlogPost.OrderByDescending(x => x.Id).ToList())
            {
                BlogPostViewModel blogPost = new BlogPostViewModel(item);
                blogPosts.Add(blogPost);
            }
          
            return PartialView(blogPosts.ToPagedList(paginaNumero, paginaTamanho));

          
        }
             
        public ActionResult Artigo(string slugTitle)
        {
            BlogVarellaMotosEntities context = new BlogVarellaMotosEntities();           
            BlogPost artigo = context.BlogPost.FirstOrDefault(x => x.SlugTitle == slugTitle);           

            if (artigo == null)
            {
               return RedirectToAction("Index");            
            }

            BlogPostViewModel blogPostViewModel = new BlogPostViewModel(artigo);
            return View(blogPostViewModel);
        }            

     
    }
}

Blog/BlogVarellaMotos/Views/Admin/BlogPosts.cshtml
@model PagedList.IPagedList<BlogVarellaMotos.Models.BlogPostViewModel>

@{
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}
<br />
<br />
<p>
    @Html.ActionLink("Criar novo artigo", "CreateBlogPost",null, new { @class = "btn btn-success" })
</p>
<br />
<table class="table">
    <tr>
        <th>
            Título
        </th>
        <th>
            Sub-título
        </th>
        <th>
            Data de criação
        </th>
        <th>
            Ações
        </th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Title)
        </td>
        <td width="30%">
            @Html.DisplayFor(modelItem => item.SubTitle)
        </td>
        <td>
            @Convert.ToDateTime(Html.DisplayFor(modelItem => item.DateCreated).ToString()).ToShortDateString()
        </td>
        <td>
            @Html.ActionLink("Editar", "EditBlogPost", new { id = item.Id }, new { @class = "btn btn-default" })
            @Html.ActionLink("Visualisar", "Artigo", "Blog", new { slugTitle = item.SlugTitle }, new { target = "_blank", @class = "btn btn-default" })
            @Html.ActionLink("Excluir", "ConfirmDeleteBlogPost", new { id = item.Id }, new { @class = "btn btn-default" })
        </td>
    </tr>
}

</table>

<br />
<br />
<div class="col-md-12 text-center">
    <div class="row">

        Página @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) de @Model.PageCount

        @if (Model.HasPreviousPage)
        {
            @Html.ActionLink("<<", "Index", new { pagina = 1, sortOrder = ViewBag.CurrentSort, currentFilter = ViewBag.CurrentFilter })
            @Html.Raw(" ");
            @Html.ActionLink("< Anterior", "Index", new { pagina = Model.PageNumber - 1, sortOrder = ViewBag.CurrentSort, currentFilter = ViewBag.CurrentFilter })
        }
        else
        {
            @:<<
            @Html.Raw(" ");
            @:< Anterior
        }

        @if (Model.HasNextPage)
        {
            @Html.ActionLink("Próxima >", "Index", new { pagina = Model.PageNumber + 1, sortOrder = ViewBag.CurrentSort, currentFilter = ViewBag.CurrentFilter })
            @Html.Raw(" ");
            @Html.ActionLink(">>", "Index", new { pagina = Model.PageCount, sortOrder = ViewBag.CurrentSort, currentFilter = ViewBag.CurrentFilter })
        }
        else
        {
            @:Próxima >
            @Html.Raw(" ")
            @:>>
        }
    </div>
</div>
<br />
<br />

Blog/BlogVarellaMotos/Views/Admin/ConfirmDeleteBlogPost.cshtml
@model BlogVarellaMotos.Models.BlogPostViewModel

@{
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

<br />
<br />
<br />

<h3>Tem certeza de que deseja exlcluir este artigo?</h3>
<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Title)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Title)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.SubTitle)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SubTitle)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Body)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Body)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.MetaDescription)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MetaDescription)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ImagePath)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ImagePath)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.SlugTitle)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SlugTitle)
        </dd>

    </dl>

    @using (Html.BeginForm("DeleteBlogPost", "Admin", new { id = Model.Id }, FormMethod.Post, null))
    {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-success"/> |
            @Html.ActionLink("Voltar", "Index")
        </div>
    }
</div>

Blog/BlogVarellaMotos/Views/Admin/CreateBlogPost.cshtml
@model BlogVarellaMotos.Models.BlogPostViewModel

@{
    ViewBag.Title = "CreateBlogPost";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";

}

<br />
<br />
<br />

<h2>Criar artigo</h2>

@using (Html.BeginForm("CreateBlogPost", "Admin", null, FormMethod.Post,
                              new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            <label class="control-label col-md-2">Título</label>
            <div class="col-md-10">
                @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <label class="control-label col-md-2">Sub-título</label>
            <div class="col-md-10">
                @Html.EditorFor(model => model.SubTitle, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.SubTitle, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <label class="control-label col-md-2">Texto</label>
            <div class="col-md-10">
                @Html.TextAreaFor(model => model.Body, new { @class = "form-control", @rows = "5", @id = "textarea-editor" })
                @Html.ValidationMessageFor(model => model.Body, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <label class="control-label col-md-2">Descrição SEO</label>
            <div class="col-md-10">
                @Html.TextAreaFor(model => model.MetaDescription, new { @class = "form-control", @rows = "5" })
                @Html.ValidationMessageFor(model => model.MetaDescription, "", new { @class = "text-danger" })
                <div class="col-md-10" hidden>
                    @Html.EditorFor(model => model.ImagePath, new { htmlAttributes = new { @class = "form-control" } })
                </div>
            </div>
        </div>

        <div class="form-group">
            <div class="row">
                <div class="col-md-10 col-lg-offset-2">
                    <p style="color:red">A imagem deve possuir no mínimo 165px de altura e 360px de largura, caso contrário não será exibida ná página principal</p>
                </div>
            </div>
            <div class="row">
                <label class="control-label col-md-2">Imagem</label>
                <div class="col-md-10">
                    <div class="editor-field">
                        <input type="file" name="UploadImage" title="Escolha uma imagem" class="input-files" accept='image/*' />
                    </div>
                    @Html.ValidationMessageFor(model => model.ImagePath, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Salvar" class="btn btn-success" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Voltar", "Index", null, new { @class = "btn btn-default" })
</div>

<br />
<br />

Blog/BlogVarellaMotos/Views/Admin/EditBlogPost.cshtml
@model BlogVarellaMotos.Models.BlogPostViewModel
@using BlogVarellaMotos.Framework;

@{
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

<br />
<br />
<br />
<br />

<h2>Editar artigo</h2>

@using (Html.BeginForm("EditBlogPost", "Admin", null, FormMethod.Post,
                              new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            <label class="control-label col-md-2">Título</label>
            <div class="col-md-10">
                @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <label class="control-label col-md-2">Sub-título</label>
            <div class="col-md-10">
                @Html.EditorFor(model => model.SubTitle, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.SubTitle, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <label class="control-label col-md-2">Texto</label>
            <div class="col-md-10">
                @Html.TextAreaFor(model => model.Body, new { @class = "form-control", @rows = "5", @id = "textarea-editor" })
                @Html.ValidationMessageFor(model => model.Body, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <label class="control-label col-md-2">Descrição SEO</label>
            <div class="col-md-10">
                @Html.TextAreaFor(model => model.MetaDescription, new { @class = "form-control", @rows = "5" })
                @Html.ValidationMessageFor(model => model.MetaDescription, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <label class="control-label col-md-2">Visualização</label>
            <div class="col-md-10">
                <img src="@Url.Content(Helper.ConcatUrlWithDiretorio(Model.ImagePath)).ToString().Replace("/imagens/","/blog/imagens/")" width="200" alt="@Model.Title" title="@Model.SubTitle" />
                @*@Html.LabelFor(model => model.ImagePath, htmlAttributes: new { @class = "control-label col-md-2" })*@
                <div class="col-md-10" hidden>
                    @Html.EditorFor(model => model.ImagePath, new { htmlAttributes = new { @class = "form-control" } })
                </div>
            </div>
        </div>

        <div class="form-group">
            <div class="row">
                <div class="col-md-10 col-lg-offset-2">
                    <p style="color:red">A imagem deve possuir no mínimo 165px de altura e 360px de largura, caso contrário não será exibida ná página principal</p>
                </div>
            </div>
            <div class="row">
                <label class="control-label col-md-2">Imagem</label>
                <div class="col-md-10">
                    <div class="editor-field">
                        <input type="file" name="UploadImage" title="Escolha uma imagem" class="input-files" accept='image/*' />
                    </div>
                    @Html.ValidationMessageFor(model => model.ImagePath, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Salvar" class="btn btn-success" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Voltar", "Index", null, new { @class="btn btn-default"})
</div>

<br />
<br />

Blog/BlogVarellaMotos/Views/Admin/Index.cshtml
@{
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}
<br />
<br />
<br />
<div class="col-md-12">
    <div class="row">
        <h1>Artigos</h1>
        <div>
            @Html.Action("BlogPosts", "Admin")
        </div>
    </div>
</div>